var angular = requirejs(['angular']);
requirejs(['csslint']);
var css = requirejs(['css/index']);
var CodeMirror = requirejs(['codemirror/lib/codemirror']);
requirejs(['codemirror/mode/css/css']);
requirejs(['codemirror/mode/xml/xml']);
requirejs(['codemirror/mode/javascript/javascript']);
requirejs(['codemirror/mode/htmlmixed/htmlmixed']);
requirejs(['codemirror/addon/selection/active-line']);
requirejs(['codemirror/addon/lint/lint']);
requirejs(['codemirror/addon/lint/css-lint']);
requirejs(['codemirror/addon/fold/foldcode']);
requirejs(['codemirror/addon/fold/foldgutter']);
requirejs(['codemirror/addon/fold/brace-fold']);
requirejs(['codemirror/addon/fold/xml-fold']);
requirejs(['codemirror/addon/fold/comment-fold']);
requirejs(['ui-codemirror']);
requirejs(['emmet/emmet']);
requirejs(['lorem']);
requirejs(['app']);
